# TTS Beta FL — Kaggle GPU bootstrap (auto-generated by kaggle_render_driver.py)
import os, subprocess, sys, urllib.request

SHA       = "f15d49708349cf8f2819da89c1b2a56b1cfa6944"
REPO      = "stromplayz/TTS-Beta-FL"
EPISODE   = "scripts/episodes/cochlea.txt"
STEM      = "cochlea"
ENGINE    = "voxcpm"
MODEL_ID  = "openbmb/VoxCPM2"
TIMESTEPS = "10"
CFG       = "2.0"

BASE = f"https://raw.githubusercontent.com/{REPO}/{SHA}"
print(f"[kernel] repo={REPO} sha={SHA[:8]} episode={EPISODE}", flush=True)
print(f"[kernel] engine={ENGINE} model={MODEL_ID} timesteps={TIMESTEPS} cfg={CFG}", flush=True)

subprocess.run([sys.executable, "-m", "pip", "install", "-q",
                "voxcpm==2.0.3", "soundfile>=0.12.1", "numpy>=1.26"], check=True)

urllib.request.urlretrieve(f"{BASE}/scripts/generate_tts.py", "generate_tts.py")
os.makedirs("episode", exist_ok=True)
urllib.request.urlretrieve(f"{BASE}/{EPISODE}", f"episode/{STEM}.txt")

cmd = [sys.executable, "generate_tts.py",
       "--episode", f"episode/{STEM}.txt",
       "--engine", ENGINE, "--model-id", MODEL_ID,
       "--timesteps", TIMESTEPS, "--cfg", CFG,
       "--outdir", "/kaggle/working"]
print("[kernel] RUN:", " ".join(cmd), flush=True)
subprocess.run(cmd, check=True)
print("[kernel] DONE — audio files are in /kaggle/working", flush=True)
