#!/usr/bin/env python3
"""TTS Beta FL — push a render job to Kaggle's free GPU and pull the audio back.

Flow (the "Kaggle loophole"):
  GitHub Actions  ──kaggle kernels push──►  Kaggle kernel (free GPU)
  Actions polls   ◄──kaggle kernels status──  kernel renders the episode
  Actions downloads ◄─kaggle kernels output── /kaggle/working/*.wav|mp3|meta

The kernel itself is a tiny bootstrap: it downloads scripts/generate_tts.py and
the episode .txt from this repo at the exact commit SHA, installs voxcpm, and
runs the very same renderer used on Actions/Codespaces — just on a GPU.
"""
from __future__ import annotations

import argparse
import json
import os
import re
import shutil
import subprocess
import sys
import time
from datetime import datetime, timezone
from pathlib import Path

# ----------------------------------------------------------------------------
# Time estimator — calibrated on a real run:
#   cochlea (1,486 words / 56 chunks) on Kaggle Tesla T4, VoxCPM2, timesteps=10
#   synthesis 19.3 min (20.7 s/chunk) + 2.4 min fixed (install, model, anchor)
# ----------------------------------------------------------------------------
FIXED_MIN_GPU = 2.4          # pip install + VoxCPM2 download/load + anchor
SEC_PER_CHUNK_GPU = 20.7     # T4, VoxCPM2 @ 48 kHz, timesteps=10
WORDS_PER_CHUNK = 26.5       # from the same calibration run
FIXED_MIN_KOKORO = 0.5
SEC_PER_CHUNK_KOKORO = 1.2


def estimate_minutes(words: int, engine: str = "voxcpm") -> dict:
    """Return an ETA dict calibrated from real Kaggle GPU runs."""
    chunks = max(1, round(words / WORDS_PER_CHUNK))
    if engine == "kokoro":
        minutes = FIXED_MIN_KOKORO + chunks * SEC_PER_CHUNK_KOKORO / 60
    else:
        minutes = FIXED_MIN_GPU + chunks * SEC_PER_CHUNK_GPU / 60
    return {"words": words, "chunks_est": chunks,
            "eta_render_min": round(minutes, 1)}


def count_words(txt: Path) -> int:
    lines = [ln for ln in txt.read_text(encoding="utf-8").splitlines()
             if not ln.strip().startswith("#")]
    return len(" ".join(lines).split())

TEMPLATE = '''\
# TTS Beta FL — Kaggle GPU bootstrap (auto-generated by kaggle_render_driver.py)
import os, subprocess, sys, urllib.request

SHA       = "__SHA__"
REPO      = "__REPO__"
EPISODE   = "__EPISODE__"
STEM      = "__STEM__"
ENGINE    = "__ENGINE__"
MODEL_ID  = "__MODEL_ID__"
TIMESTEPS = "__TIMESTEPS__"
CFG       = "__CFG__"

BASE = f"https://raw.githubusercontent.com/{REPO}/{SHA}"
print(f"[kernel] repo={REPO} sha={SHA[:8]} episode={EPISODE}", flush=True)
print(f"[kernel] engine={ENGINE} model={MODEL_ID} timesteps={TIMESTEPS} cfg={CFG}", flush=True)

subprocess.run([sys.executable, "-m", "pip", "install", "-q",
                "voxcpm==2.0.3", "soundfile>=0.12.1", "numpy>=1.26"], check=True)

urllib.request.urlretrieve(f"{BASE}/scripts/generate_tts.py", "generate_tts.py")
os.makedirs("episode", exist_ok=True)
urllib.request.urlretrieve(f"{BASE}/{EPISODE}", f"episode/{STEM}.txt")

cmd = [sys.executable, "generate_tts.py",
       "--episode", f"episode/{STEM}.txt",
       "--engine", ENGINE, "--model-id", MODEL_ID,
       "--timesteps", TIMESTEPS, "--cfg", CFG,
       "--outdir", "/kaggle/working"]
print("[kernel] RUN:", " ".join(cmd), flush=True)
subprocess.run(cmd, check=True)
print("[kernel] DONE — audio files are in /kaggle/working", flush=True)
'''


def sh(cmd: list[str], **kw) -> subprocess.CompletedProcess:
    print("+", " ".join(cmd), flush=True)
    return subprocess.run(cmd, check=kw.pop("check", True), **kw)


def kaggle_username() -> str:
    """Kaggle username from env, or from ~/.kaggle/kaggle.json (how the CLI reads it)."""
    user = os.environ.get("KAGGLE_USERNAME")
    if user:
        return user
    cfg = Path.home() / ".kaggle" / "kaggle.json"
    if cfg.exists():
        return json.loads(cfg.read_text(encoding="utf-8"))["username"]
    sys.exit("KAGGLE_USERNAME env or ~/.kaggle/kaggle.json required")


def main() -> None:
    ap = argparse.ArgumentParser(description="TTS Beta FL Kaggle GPU driver")
    ap.add_argument("--episode", required=True, help="episode .txt path inside the repo")
    ap.add_argument("--repo", default="stromplayz/TTS-Beta-FL")
    ap.add_argument("--sha", default=os.environ.get("GITHUB_SHA", "main"))
    ap.add_argument("--engine", default="voxcpm")
    ap.add_argument("--model-id", default="openbmb/VoxCPM2",
                    help="48 kHz flagship recommended on GPU")
    ap.add_argument("--timesteps", default="10")
    ap.add_argument("--cfg", default="2.0")
    ap.add_argument("--slug", default=None, help="kernel slug (default: tts-fl-<stem>)")
    ap.add_argument("--out", default="rendered", help="where to place downloaded audio")
    ap.add_argument("--timeout-min", type=int, default=80)
    ap.add_argument("--poll-sec", type=int, default=45)
    ap.add_argument("--estimate-only", action="store_true",
                    help="print the calibrated ETA for the episode and exit (no Kaggle run)")
    args = ap.parse_args()

    stem = Path(args.episode).stem

    # ---- estimate-only mode (used by the workflow's 'Estimate render time' step)
    if args.estimate_only:
        est = estimate_minutes(count_words(Path(args.episode)), args.engine)
        print(json.dumps(est, indent=2))
        return

    words = count_words(Path(args.episode))
    est = estimate_minutes(words, args.engine)
    print(f"[driver] ESTIMATE · {est['words']} words ≈ {est['chunks_est']} chunks · "
          f"expected render ≈ {est['eta_render_min']} min (+0-5 min Kaggle queue)", flush=True)

    slug = (args.slug or f"tts-fl-{stem}")[:50].lower()
    kernel_id = f"{kaggle_username()}/{slug}"
    t_push = time.time()

    # ---- build the kernel payload -------------------------------------------------
    kdir = Path(".kaggle-kernel")
    if kdir.exists():
        shutil.rmtree(kdir)
    kdir.mkdir()

    src = (TEMPLATE
           .replace("__SHA__", args.sha)
           .replace("__REPO__", args.repo)
           .replace("__EPISODE__", args.episode)
           .replace("__STEM__", stem)
           .replace("__ENGINE__", args.engine)
           .replace("__MODEL_ID__", args.model_id)
           .replace("__TIMESTEPS__", str(args.timesteps))
           .replace("__CFG__", str(args.cfg)))
    (kdir / "render.py").write_text(src, encoding="utf-8")

    meta = {
        "id": kernel_id,
        "title": slug.replace("-", " ").title()[:20],
        "code_file": "render.py",
        "language": "python",
        "kernel_type": "script",
        "is_private": "true",
        "enable_gpu": "true",
        "enable_internet": "true",
        "dataset_sources": [],
        "competition_sources": [],
        "kernel_sources": [],
    }
    (kdir / "kernel-metadata.json").write_text(json.dumps(meta, indent=2), encoding="utf-8")

    # ---- push and wait -------------------------------------------------------------
    print(f"[driver] pushing kernel {kernel_id} (GPU) …", flush=True)
    sh(["kaggle", "kernels", "push", "-p", str(kdir)])

    print(f"[driver] polling every {args.poll_sec}s (max {args.timeout_min} min) …", flush=True)
    t0, status = time.time(), None
    while time.time() - t0 < args.timeout_min * 60:
        time.sleep(args.poll_sec)
        r = subprocess.run(["kaggle", "kernels", "status", kernel_id],
                           capture_output=True, text=True)
        out = (r.stdout + r.stderr).lower()
        if "complete" in out:
            status = "complete"
            break
        if "error" in out or "cancel" in out:
            status = "error"
            break
        print(f"[driver] {(time.time() - t0) / 60:5.1f} min · queued/running…", flush=True)

    if status != "complete":
        print(f"[driver] kernel finished with status={status!r} — "
              f"inspect it at https://www.kaggle.com/code/{kernel_id}", flush=True)
        sys.exit(2)

    t_done = time.time()
    render_min = (t_done - t_push) / 60
    print(f"[driver] TIMING · push→complete = {render_min:.1f} min "
          f"(estimate was {est['eta_render_min']} min)", flush=True)

    # ---- pull the audio back (stage first, keep only the deliverables) --------
    outdir = Path(args.out)
    staging = Path(".kaggle-out-staging")
    if staging.exists():
        shutil.rmtree(staging)
    staging.mkdir(parents=True)
    outdir.mkdir(parents=True, exist_ok=True)
    sh(["kaggle", "kernels", "output", kernel_id, "-p", str(staging), "-o"])

    keep = [f"{stem}.wav", f"{stem}.mp3", f"{stem}.meta.json"]
    missing = [f for f in keep if not (staging / f).exists()]
    if missing:
        print(f"[driver] WARNING missing outputs: {missing}", flush=True)
        sys.exit(3)
    for f in keep:
        shutil.move(str(staging / f), str(outdir / f))
    shutil.rmtree(staging, ignore_errors=True)

    total_min = (time.time() - t_push) / 60
    timing = {**est,
              "actual_push_to_complete_min": round(render_min, 1),
              "actual_total_min": round(total_min, 1),
              "kernel": kernel_id,
              "started_at_utc": datetime.now(timezone.utc).isoformat()}
    (outdir / f"{stem}.timing.json").write_text(json.dumps(timing, indent=2) + "\n",
                                                encoding="utf-8")
    print(f"[driver] TIMING · total (push→download) = {total_min:.1f} min", flush=True)
    print(f"[driver] SUCCESS — delivered to {outdir}/: {', '.join(keep)}", flush=True)


if __name__ == "__main__":
    main()
