#!/usr/bin/env python3
"""TTS Beta FL — push a render job to Kaggle's free GPU and pull the audio back.

Flow (the "Kaggle loophole"):
  GitHub Actions  ──kaggle kernels push──►  Kaggle kernel (free GPU)
  Actions polls   ◄──kaggle kernels status──  kernel renders the episode
  Actions downloads ◄─kaggle kernels output── /kaggle/working/*.wav|mp3|meta

The kernel itself is a tiny bootstrap: it downloads scripts/generate_tts.py and
the episode .txt from this repo at the exact commit SHA, installs voxcpm, and
runs the very same renderer used on Actions/Codespaces — just on a GPU.
"""
from __future__ import annotations

import argparse
import json
import os
import shutil
import subprocess
import sys
import time
from pathlib import Path

TEMPLATE = '''\
# TTS Beta FL — Kaggle GPU bootstrap (auto-generated by kaggle_render_driver.py)
import os, subprocess, sys, urllib.request

SHA       = "__SHA__"
REPO      = "__REPO__"
EPISODE   = "__EPISODE__"
STEM      = "__STEM__"
ENGINE    = "__ENGINE__"
MODEL_ID  = "__MODEL_ID__"
TIMESTEPS = "__TIMESTEPS__"
CFG       = "__CFG__"

BASE = f"https://raw.githubusercontent.com/{REPO}/{SHA}"
print(f"[kernel] repo={REPO} sha={SHA[:8]} episode={EPISODE}", flush=True)
print(f"[kernel] engine={ENGINE} model={MODEL_ID} timesteps={TIMESTEPS} cfg={CFG}", flush=True)

subprocess.run([sys.executable, "-m", "pip", "install", "-q",
                "voxcpm==2.0.3", "soundfile>=0.12.1", "numpy>=1.26"], check=True)

urllib.request.urlretrieve(f"{BASE}/scripts/generate_tts.py", "generate_tts.py")
os.makedirs("episode", exist_ok=True)
urllib.request.urlretrieve(f"{BASE}/{EPISODE}", f"episode/{STEM}.txt")

cmd = [sys.executable, "generate_tts.py",
       "--episode", f"episode/{STEM}.txt",
       "--engine", ENGINE, "--model-id", MODEL_ID,
       "--timesteps", TIMESTEPS, "--cfg", CFG,
       "--outdir", "/kaggle/working"]
print("[kernel] RUN:", " ".join(cmd), flush=True)
subprocess.run(cmd, check=True)
print("[kernel] DONE — audio files are in /kaggle/working", flush=True)
'''


def sh(cmd: list[str], **kw) -> subprocess.CompletedProcess:
    print("+", " ".join(cmd), flush=True)
    return subprocess.run(cmd, check=kw.pop("check", True), **kw)


def main() -> None:
    ap = argparse.ArgumentParser(description="TTS Beta FL Kaggle GPU driver")
    ap.add_argument("--episode", required=True, help="episode .txt path inside the repo")
    ap.add_argument("--repo", default="stromplayz/TTS-Beta-FL")
    ap.add_argument("--sha", default=os.environ.get("GITHUB_SHA", "main"))
    ap.add_argument("--engine", default="voxcpm")
    ap.add_argument("--model-id", default="openbmb/VoxCPM2",
                    help="48 kHz flagship recommended on GPU")
    ap.add_argument("--timesteps", default="10")
    ap.add_argument("--cfg", default="2.0")
    ap.add_argument("--slug", default=None, help="kernel slug (default: tts-fl-<stem>)")
    ap.add_argument("--out", default="output", help="where to place downloaded audio")
    ap.add_argument("--timeout-min", type=int, default=80)
    ap.add_argument("--poll-sec", type=int, default=45)
    args = ap.parse_args()

    stem = Path(args.episode).stem
    slug = (args.slug or f"tts-fl-{stem}")[:50].lower()
    kernel_id = f"{os.environ['KAGGLE_USERNAME']}/{slug}"

    # ---- build the kernel payload -------------------------------------------------
    kdir = Path(".kaggle-kernel")
    if kdir.exists():
        shutil.rmtree(kdir)
    kdir.mkdir()

    src = (TEMPLATE
           .replace("__SHA__", args.sha)
           .replace("__REPO__", args.repo)
           .replace("__EPISODE__", args.episode)
           .replace("__STEM__", stem)
           .replace("__ENGINE__", args.engine)
           .replace("__MODEL_ID__", args.model_id)
           .replace("__TIMESTEPS__", str(args.timesteps))
           .replace("__CFG__", str(args.cfg)))
    (kdir / "render.py").write_text(src, encoding="utf-8")

    meta = {
        "id": kernel_id,
        "title": slug.replace("-", " ").title()[:20],
        "code_file": "render.py",
        "language": "python",
        "kernel_type": "script",
        "is_private": "true",
        "enable_gpu": "true",
        "enable_internet": "true",
        "dataset_sources": [],
        "competition_sources": [],
        "kernel_sources": [],
    }
    (kdir / "kernel-metadata.json").write_text(json.dumps(meta, indent=2), encoding="utf-8")

    # ---- push and wait -------------------------------------------------------------
    print(f"[driver] pushing kernel {kernel_id} (GPU) …", flush=True)
    sh(["kaggle", "kernels", "push", "-p", str(kdir)])

    print(f"[driver] polling every {args.poll_sec}s (max {args.timeout_min} min) …", flush=True)
    t0, status = time.time(), None
    while time.time() - t0 < args.timeout_min * 60:
        time.sleep(args.poll_sec)
        r = subprocess.run(["kaggle", "kernels", "status", kernel_id],
                           capture_output=True, text=True)
        out = (r.stdout + r.stderr).lower()
        if "complete" in out:
            status = "complete"
            break
        if "error" in out or "cancel" in out:
            status = "error"
            break
        print(f"[driver] {(time.time() - t0) / 60:5.1f} min · queued/running…", flush=True)

    if status != "complete":
        print(f"[driver] kernel finished with status={status!r} — "
              f"inspect it at https://www.kaggle.com/code/{kernel_id}", flush=True)
        sys.exit(2)

    # ---- pull the audio back --------------------------------------------------------
    outdir = Path(args.out)
    outdir.mkdir(parents=True, exist_ok=True)
    sh(["kaggle", "kernels", "output", kernel_id, "-p", str(outdir), "-o"])

    expected = [f"{stem}.wav", f"{stem}.mp3", f"{stem}.meta.json"]
    missing = [f for f in expected if not (outdir / f).exists()]
    if missing:
        print(f"[driver] WARNING missing outputs: {missing}", flush=True)
        sys.exit(3)

    print(f"[driver] SUCCESS — downloaded: {', '.join(expected)}", flush=True)


if __name__ == "__main__":
    main()
