#!/usr/bin/env python3
"""Focus Cast — push render jobs to Kaggle's free GPU and pull the audio back.

Flow (the "Kaggle loophole"):
  GitHub Actions  ──kaggle kernels push──►  Kaggle kernel (free GPU)
  Actions polls   ◄──kaggle kernels status──  kernel renders the episodes
  Actions downloads ◄─kaggle kernels output── /kaggle/working/**.wav|mp3|meta

Batch-aware: accepts one or many episode scripts. Each script's '# Key: value'
header decides engine (kokoro | voxcpm), narration mode and the destination
folder rendered/<series-NN-slug>/season-NN-slug/ep-NN-title-slug/.
"""
from __future__ import annotations

import argparse
import json
import os
import re
import shutil
import subprocess
import sys
import time
from datetime import datetime, timezone
from pathlib import Path

# ----------------------------------------------------------------------------
# Time estimators (calibrated on real runs; refine as more renders finish)
#   VoxCPM2 @ T4, timesteps=10 : cochlea 1,486 w → 21.7 min (20.7 s/chunk)
#   Kokoro-82M @ T4            : ~30× realtime for spoken word
# ----------------------------------------------------------------------------
FIXED_MIN_GPU = 2.4
SEC_PER_CHUNK_GPU = 20.7
WORDS_PER_CHUNK = 26.5
KOKORO_SHARED_MIN = 2.0      # pip install + model download (once per batch)
KOKORO_PER_EP_MIN = 0.5
KOKORO_PER_WORD_SEC = 0.024  # ≈ 25× realtime incl. per-turn overhead

TEMPLATE = '''\
# Focus Cast — Kaggle GPU bootstrap (auto-generated by kaggle_render_driver.py)
import json, os, subprocess, sys, urllib.request

SHA      = "__SHA__"
REPO     = "__REPO__"
BASE     = f"https://raw.githubusercontent.com/{REPO}/{SHA}"
JOBS     = __JOBS__            # list of dicts: script path, stem, dest dir
ENGINE   = __ENGINE__          # "auto" | "kokoro" | "voxcpm"
MODEL_ID = "__MODEL_ID__"
TIMESTEPS = "__TIMESTEPS__"
CFG       = "__CFG__"
BITRATE   = "__BITRATE__"

print(f"[kernel] repo={REPO} sha={SHA[:8]} · {len(JOBS)} episode(s)", flush=True)

subprocess.run([sys.executable, "-m", "pip", "install", "-q",
                "kokoro>=0.9.4", "soundfile>=0.12.1", "numpy>=1.26"], check=True)
if ENGINE != "kokoro":
    subprocess.run([sys.executable, "-m", "pip", "install", "-q", "voxcpm==2.0.3"], check=True)
subprocess.run("command -v espeak-ng >/dev/null || (apt-get update -qq && apt-get install -y -qq espeak-ng)",
               shell=True, check=False)

for f in ["scripts/generate_tts.py", "library/presets/voices.json"]:
    dest = os.path.join("repo", f)
    os.makedirs(os.path.dirname(dest), exist_ok=True)
    urllib.request.urlretrieve(f"{BASE}/{f}", dest)

for job in JOBS:
    stem, dest_rel, script_path = job["stem"], job["dest"], job["script"]
    os.makedirs("episode", exist_ok=True)
    urllib.request.urlretrieve(f"{BASE}/{script_path}", f"episode/{stem}.txt")
    outdir = os.path.join("/kaggle/working", dest_rel)
    os.makedirs(outdir, exist_ok=True)
    cmd = [sys.executable, "repo/scripts/generate_tts.py",
           "--episode", f"episode/{stem}.txt",
           "--presets", "repo/library/presets/voices.json",
           "--outdir", outdir, "--mp3-bitrate", BITRATE]
    if ENGINE != "auto":
        cmd += ["--engine", ENGINE]
    if ENGINE == "voxcpm":
        cmd += ["--model-id", MODEL_ID, "--timesteps", TIMESTEPS, "--cfg", CFG]
    print("[kernel] RUN:", " ".join(cmd), flush=True)
    subprocess.run(cmd, check=True)

print("[kernel] DONE — audio files are in /kaggle/working", flush=True)
'''


def sh(cmd: list[str], **kw) -> subprocess.CompletedProcess:
    print("+", " ".join(cmd), flush=True)
    return subprocess.run(cmd, check=kw.pop("check", True), **kw)


def kaggle_username() -> str:
    user = os.environ.get("KAGGLE_USERNAME")
    if user:
        return user
    cfg = Path.home() / ".kaggle" / "kaggle.json"
    if cfg.exists():
        return json.loads(cfg.read_text(encoding="utf-8"))["username"]
    sys.exit("KAGGLE_USERNAME env or ~/.kaggle/kaggle.json required")


def slugify(s: str) -> str:
    s = re.sub(r"[^a-z0-9]+", "-", s.lower()).strip("-")
    return re.sub(r"-{2,}", "-", s)


def parse_header(raw_text: str) -> dict:
    hdr: dict = {}
    for ln in raw_text.splitlines():
        s = ln.strip()
        if not s.startswith("#"):
            if s:
                break
            continue
        m = re.match(r"#\s*([A-Za-z][A-Za-z0-9 '&/.-]*?)\s*:\s*(.+)$", s)
        if m:
            hdr[m.group(1).strip().lower().replace(" ", "_")] = m.group(2).strip()
    return hdr


def dest_dir_for(hdr: dict, stem: str) -> str:
    """library hierarchy: series-NN-slug/season-NN-slug/ep-NN-title-slug"""
    try:
        s_no = int(hdr.get("series_no", 0))
    except ValueError:
        s_no = 0
    series = hdr.get("series", "")
    season = hdr.get("season", "")
    title = hdr.get("title", stem)
    try:
        season_no = int(str(hdr.get("season_no", "")).split(" ")[0])
    except (ValueError, TypeError):
        season_no = 0
    try:
        ep_no = int(str(hdr.get("episode_no", "")).split(" ")[0])
    except (ValueError, TypeError):
        ep_no = 0
    if s_no and season_no and ep_no:
        return (f"series-{s_no:02d}-{slugify(series)}/"
                f"season-{season_no:02d}-{slugify(season)}/"
                f"ep-{ep_no:02d}-{slugify(title)}")
    return stem  # untagged script → flat fallback


def estimate_minutes(words_total: int, n_eps: int, engine: str) -> dict:
    if engine == "kokoro":
        minutes = (KOKORO_SHARED_MIN + n_eps * KOKORO_PER_EP_MIN
                   + words_total * KOKORO_PER_WORD_SEC / 60)
    else:
        chunks = max(1, round(words_total / WORDS_PER_CHUNK))
        minutes = FIXED_MIN_GPU + chunks * SEC_PER_CHUNK_GPU / 60
    return {"episodes": n_eps, "words_total": words_total,
            "eta_render_min": round(minutes, 1)}


def count_words(txt: Path) -> int:
    lines = [ln for ln in txt.read_text(encoding="utf-8").splitlines()
             if not ln.strip().startswith("#")]
    return len(" ".join(lines).split())


def main() -> None:
    ap = argparse.ArgumentParser(description="Focus Cast Kaggle GPU driver")
    ap.add_argument("--episode", required=True, action="append",
                    help="episode .txt path inside the repo (repeat or comma-separate for batches)")
    ap.add_argument("--repo", default="stromplayz/FocusCast")
    ap.add_argument("--sha", default=os.environ.get("GITHUB_SHA", "main"))
    ap.add_argument("--engine", default="auto", choices=["auto", "kokoro", "voxcpm"])
    ap.add_argument("--model-id", default="openbmb/VoxCPM2",
                    help="48 kHz flagship recommended on GPU")
    ap.add_argument("--timesteps", default="10")
    ap.add_argument("--cfg", default="2.0")
    ap.add_argument("--mp3-bitrate", default="96k", help="library default: 96k mono CBR")
    ap.add_argument("--slug", default=None, help="kernel slug (default: focuscast-<first stem>)")
    ap.add_argument("--out", default="rendered", help="destination root for downloaded audio")
    ap.add_argument("--no-wav", action="store_true",
                    help="keep only mp3+meta (recommended for git-committed library renders)")
    ap.add_argument("--timeout-min", type=int, default=100)
    ap.add_argument("--poll-sec", type=int, default=45)
    ap.add_argument("--estimate-only", action="store_true",
                    help="print the calibrated ETA for the batch and exit")
    args = ap.parse_args()

    # expand comma-separated episode lists
    episodes: list[str] = []
    for e in args.episode:
        episodes.extend([x.strip() for x in e.split(",") if x.strip()])

    # build the job table (script → stem → destination folder)
    jobs, words_total, engines_used = [], 0, set()
    for ep in episodes:
        p = Path(ep)
        hdr = parse_header(p.read_text(encoding="utf-8"))
        stem = p.stem
        dest = dest_dir_for(hdr, stem)
        engine = args.engine if args.engine != "auto" else hdr.get("engine", "kokoro").lower()
        engines_used.add(engine)
        words_total += count_words(p)
        jobs.append({"script": ep, "stem": stem, "dest": dest, "engine": engine})
        print(f"[driver] job: {stem} → rendered/{dest} · engine={engine}", flush=True)

    primary_engine = "kokoro" if args.engine != "voxcpm" and engines_used <= {"kokoro"} else \
                     ("voxcpm" if engines_used == {"voxcpm"} else "kokoro")
    est = estimate_minutes(words_total, len(jobs), primary_engine)

    if args.estimate_only:
        print(json.dumps(est, indent=2))
        return

    print(f"[driver] ESTIMATE · {est['episodes']} episode(s) · {est['words_total']} words · "
          f"expected render ≈ {est['eta_render_min']} min (+0-5 min Kaggle queue)", flush=True)

    slug = (args.slug or f"focuscast-{jobs[0]['stem']}")[:50].lower()
    kernel_id = f"{kaggle_username()}/{slug}"
    t_push = time.time()

    # ---- build the kernel payload -------------------------------------------------
    kdir = Path(".kaggle-kernel")
    if kdir.exists():
        shutil.rmtree(kdir)
    kdir.mkdir()

    kernel_src = (TEMPLATE
                  .replace("__SHA__", args.sha)
                  .replace("__REPO__", args.repo)
                  .replace("__JOBS__", json.dumps(jobs, indent=8))
                  .replace("__ENGINE__", repr(args.engine))
                  .replace("__MODEL_ID__", args.model_id)
                  .replace("__TIMESTEPS__", str(args.timesteps))
                  .replace("__CFG__", str(args.cfg))
                  .replace("__BITRATE__", args.mp3_bitrate))
    (kdir / "render.py").write_text(kernel_src, encoding="utf-8")

    meta = {
        "id": kernel_id,
        "title": slug.replace("-", " ").title()[:20],
        "code_file": "render.py",
        "language": "python",
        "kernel_type": "script",
        "is_private": "true",
        "enable_gpu": "true",
        "enable_internet": "true",
        "dataset_sources": [],
        "competition_sources": [],
        "kernel_sources": [],
    }
    (kdir / "kernel-metadata.json").write_text(json.dumps(meta, indent=2), encoding="utf-8")

    # ---- push and wait -------------------------------------------------------------
    print(f"[driver] pushing kernel {kernel_id} (GPU) …", flush=True)
    sh(["kaggle", "kernels", "push", "-p", str(kdir)])

    print(f"[driver] polling every {args.poll_sec}s (max {args.timeout_min} min) …", flush=True)
    t0, status = time.time(), None
    while time.time() - t0 < args.timeout_min * 60:
        time.sleep(args.poll_sec)
        r = subprocess.run(["kaggle", "kernels", "status", kernel_id],
                           capture_output=True, text=True)
        out = (r.stdout + r.stderr).lower()
        if "complete" in out:
            status = "complete"
            break
        if "error" in out or "cancel" in out:
            status = "error"
            break
        print(f"[driver] {(time.time() - t0) / 60:5.1f} min · queued/running…", flush=True)

    if status != "complete":
        print(f"[driver] kernel finished with status={status!r} — "
              f"inspect it at https://www.kaggle.com/code/{kernel_id}", flush=True)
        sys.exit(2)

    render_min = (time.time() - t_push) / 60
    print(f"[driver] TIMING · push→complete = {render_min:.1f} min "
          f"(estimate was {est['eta_render_min']} min)", flush=True)

    # ---- pull the audio back (stage, then map into the library hierarchy) ----------
    outroot = Path(args.out)
    staging = Path(".kaggle-out-staging")
    if staging.exists():
        shutil.rmtree(staging)
    staging.mkdir(parents=True)
    sh(["kaggle", "kernels", "output", kernel_id, "-p", str(staging), "-o"])

    delivered, missing = [], []
    for job in jobs:
        stem, dest = job["stem"], job["dest"]
        src_dir = staging / dest
        want = [f"{stem}.mp3", f"{stem}.meta.json"]
        optional = [] if args.no_wav else [f"{stem}.wav"]
        found_dir = src_dir if src_dir.exists() else staging
        if not all((found_dir / f).exists() for f in want):
            missing.append(stem)
            continue
        target = outroot / dest
        target.mkdir(parents=True, exist_ok=True)
        for f in want + optional:
            if (found_dir / f).exists():
                shutil.move(str(found_dir / f), str(target / f))
        delivered.append(f"{dest}/{stem}.mp3")
    shutil.rmtree(staging, ignore_errors=True)

    if missing:
        print(f"[driver] WARNING missing outputs: {missing}", flush=True)
        sys.exit(3)

    total_min = (time.time() - t_push) / 60
    timing = {**est,
              "actual_push_to_complete_min": round(render_min, 1),
              "actual_total_min": round(total_min, 1),
              "kernel": kernel_id,
              "delivered": delivered,
              "started_at_utc": datetime.now(timezone.utc).isoformat()}
    timing_path = outroot / f"{slug}.timing.json"
    timing_path.write_text(json.dumps(timing, indent=2) + "\n", encoding="utf-8")
    print(f"[driver] TIMING · total (push→download) = {total_min:.1f} min → {timing_path}",
          flush=True)
    print(f"[driver] SUCCESS — {len(delivered)} episode(s) delivered:", flush=True)
    for d in delivered:
        print(f"[driver]   rendered/{d}", flush=True)


if __name__ == "__main__":
    main()
